// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });
import styles from "@/styles/Home.module.css";
import Head from "next/head";

import { Box, Tooltip, Typography } from "@mui/material";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import Details from "../components/details";
import ImageBox from "../components/ImageBox";
import { useSelector } from "react-redux";


const Index = () => {
    let data = useSelector(store => store.cartSection)
    let total = 0.00;
    let totalLength = data.filter(abc => {
        if (abc.added) {
            total += abc.price;
            return true;
        }
    })
    return (
        <>
            <Head>
                <title>Shopping Basket</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box
                sx={{ minHeight: "100vh", maxWidth: "960px", margin: "auto", padding: "40px 20px", paddingBottom: "100px" }}
            >
                {/* Dsigner Name */}
                <Typography
                    sx={{
                        textAlign: "center", fontWeight: "bold",
                        marginBottom: "20px", color: "grey",
                        textDecoration: "underline"
                    }}
                    variant="h4"
                >
                    Shopping Basket By{" "}
                    <Tooltip title="Automatic Break System" arrow placement="top">
                        A.B.S
                    </Tooltip>
                </Typography>
                {/* map inside of images */}
                <Box sx={{
                    display: "flex",
                    '@media (max-width: 885px)': {
                        display: 'block '
                    }
                }}>
                    {data.map((product) => {
                        return <ImageBox key={product.id} data={product} />
                    })}
                </Box>

                {/* list of items */}
                <Typography sx={{ fontWeight: "600", fontSize: "21px", color: "rgba(31, 49, 211, 0.979)", marginTop: "20px" }}  >Shopping Basket</Typography>
                <Typography sx={{ marginBottom: "8px" }} >You have {totalLength.length} items in your basket</Typography>
                <Box>
                    {data.map((product) => {
                        if (product.added) {
                            return <Details key={product.id} data={product} />
                        }
                    })}
                </Box>
                <Typography
                    sx={{ fontWeight: "600", fontSize: "30px", float: "right", marginRight: "20px" }}
                >
                    £{total}
                </Typography>

                {/* the end */}
            </Box>
        </>
    )
}

export default Index